version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
       - ./logs/mysql:/var/log/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./app:/var/www/html
       - ./logs/apache2:/var/log/apache2
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   pma:
     depends_on:
      - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     volumes:
       - ./phpmyadmin/sessions:/sessions
     environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=db
       - PMA_USER=wordpress
       - PMA_PASSWORD=wordpress